services:
  - type: web
    # …
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    releaseCommand: |
      python manage.py migrate
      python manage.py loaddata store/fixtures/admin_user.json
      python manage.py loaddata store/fixtures/products.json
    startCommand: gunicorn grape_shop.wsgi:application --bind 0.0.0.0:$PORT