services:
  - type: web
    name: electronics-shop
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn grape_shop.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: '1'

databases:
  - name: electronics-shop-db
    plan: free